name = "clash-config-parser"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[build]]
command = "npm run build"

[build.upload]
format = "directory"
dir = "dist"
